import "../App.css";

function CommercialCreditVision({ base }) {
  const yourInstitution = base.data.report.productSec.creditProfileSummarySec.yourInstitution;
  const outsideInstitution =
    base.data.report.productSec.creditProfileSummarySec.outsideInstitution;
  const total = base.data.report.productSec.creditProfileSummarySec.total;
  return (
    <div style={{ display: "flex", justifyContent: "center", margin: 40 }}>
      <table cellspacing="0" cellpadding="0">
        <thead>
          <tr>
            <th colspan="12">
              <p>Commercial CreditVision&reg;</p>
            </th>
          </tr>
          <tr>
            <td colspan="12">
              <p>
                Commercial CreditVision(CCV) algorithms available but your
                institution has an not subscribed to it. For subscription
                details, kindly contact your institutions nodal officer.
              </p>
            </td>
          </tr>
          <tr>
            <th colspan="12">
              <p>4. Credit Profile Summary</p>
              <p>
                *CF - Credit facility, % - Wallet share of your Institution vs
                Others; ** Delinquent: SMA 0 onwards
              </p>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td rowspan="2"></td>
            <td rowspan="2">
              <p>Total Lenders</p>
            </td>
            <td colspan="2">
              <p>TotalCF*(s)</p>
            </td>
            <td rowspan="2">
              <p>Open CF</p>
            </td>
            <td colspan="2">
              <p>Total Outstanding(in ₹)</p>
            </td>
            <td rowspan="2">
              <p>Latest CF Opened Date </p>
            </td>
            <td colspan="2">
              <p>**Delinquent CF</p>
            </td>
            <td colspan="2">
              <p>Delinquent Outstanding (in ₹)</p>
            </td>
          </tr>
          <tr>
            <td>
              <p>Borrower</p>
            </td>
            <td>
              <p>Guarantor</p>
            </td>
            <td>
              <p>Borrower</p>
            </td>
            <td>
              <p>Guarantor</p>
            </td>
            <td>
              <p>Borrower</p>
            </td>
            <td>
              <p>Guarantor</p>
            </td>
            <td>
              <p>Borrower</p>
            </td>
            <td>
              <p>Guarantor</p>
            </td>
          </tr>
          <tr>
            <td>
              <p>Your Institution</p>
            </td>
            <td>
              <p>
                <span>
                  {yourInstitution.totalLenders}
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {yourInstitution.totalCf.borrower}
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {yourInstitution.totalCf.guarantor}
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>{yourInstitution.openCf}</span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {
                    yourInstitution.totalOutstanding
                      .borrower
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {
                    yourInstitution.totalOutstanding
                      .guarantor
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {yourInstitution.latestCFOpenedDate}
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {
                    yourInstitution.delinquentCf
                      .borrower
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {
                    yourInstitution.delinquentCf
                      .guarantor
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {
                    yourInstitution.delinquentOutstanding.borrower
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {
                    yourInstitution
                      .delinquentOutstanding.guarantor
                  }
                </span>
              </p>
            </td>
          </tr>
          <tr>
            <td>
              <p> Other Public Sector Banks</p>
            </td>
            <td>
              <p>
                <span>
                  {outsideInstitution.otherPublicSectorBanks.totalLenders}
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {outsideInstitution.otherPublicSectorBanks.totalCf.borrower}
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {outsideInstitution.otherPublicSectorBanks.totalCf.guarantor}
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>{outsideInstitution.otherPublicSectorBanks.openCf}</span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {
                    outsideInstitution.otherPublicSectorBanks.totalOutstanding
                      .borrower
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {
                    outsideInstitution.otherPublicSectorBanks.totalOutstanding
                      .guarantor
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {outsideInstitution.otherPublicSectorBanks.latestCFOpenedDate}
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {
                    outsideInstitution.otherPublicSectorBanks.delinquentCf
                      .borrower
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {
                    outsideInstitution.otherPublicSectorBanks.delinquentCf
                      .guarantor
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {
                    outsideInstitution.otherPublicSectorBanks
                      .delinquentOutstanding.borrower
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {
                    outsideInstitution.otherPublicSectorBanks
                      .delinquentOutstanding.guarantor
                  }
                </span>
              </p>
            </td>
          </tr>
          <tr>
            <td>
              <p>Other Private Banks & Foreign Banks</p>
            </td>
            <td>
              <p>
                <span>
                  {outsideInstitution.otherPrivateForeignBanks.totalLenders}
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {outsideInstitution.otherPrivateForeignBanks.totalCf.borrower}
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {
                    outsideInstitution.otherPrivateForeignBanks.totalCf
                      .guarantor
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {outsideInstitution.otherPrivateForeignBanks.openCf}
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {
                    outsideInstitution.otherPrivateForeignBanks.totalOutstanding
                      .borrower
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {
                    outsideInstitution.otherPrivateForeignBanks.totalOutstanding
                      .guarantor
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {
                    outsideInstitution.otherPrivateForeignBanks
                      .latestCFOpenedDate
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {
                    outsideInstitution.otherPrivateForeignBanks.delinquentCf
                      .borrower
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {
                    outsideInstitution.otherPrivateForeignBanks.delinquentCf
                      .guarantor
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {
                    outsideInstitution.otherPrivateForeignBanks
                      .delinquentOutstanding.borrower
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {
                    outsideInstitution.otherPrivateForeignBanks
                      .delinquentOutstanding.guarantor
                  }
                </span>
              </p>
            </td>
          </tr>
          <tr>
            <td>
              <p>NBFCs Others</p>
            </td>
            <td>
              <p>
                <span>{outsideInstitution.nbfcOthers.totalLenders}</span>
              </p>
            </td>
            <td>
              <p>
                <span>{outsideInstitution.nbfcOthers.totalCf.borrower}</span>
              </p>
            </td>
            <td>
              <p>
                <span>{outsideInstitution.nbfcOthers.totalCf.guarantor}</span>
              </p>
            </td>
            <td>
              <p>
                <span>{outsideInstitution.nbfcOthers.openCf}</span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {outsideInstitution.nbfcOthers.totalOutstanding.borrower}
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {outsideInstitution.nbfcOthers.totalOutstanding.guarantor}
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>{outsideInstitution.nbfcOthers.latestCfOpenedDate}</span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {outsideInstitution.nbfcOthers.delinquentCf.borrower}
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {outsideInstitution.nbfcOthers.delinquentCf.guarantor}
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {outsideInstitution.nbfcOthers.delinquentOutstanding.borrower}
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {
                    outsideInstitution.nbfcOthers.delinquentOutstanding
                      .guarantor
                  }
                </span>
              </p>
            </td>
          </tr>
          <tr>
            <td>
              <p>Outside Total</p>
            </td>
            <td>
              <p>
                <span>{outsideInstitution.outsideTotal.totalLenders}</span>
              </p>
            </td>
            <td>
              <p>
                <span>{outsideInstitution.outsideTotal.totalCf.borrower}</span>
              </p>
            </td>
            <td>
              <p>
                <span>{outsideInstitution.outsideTotal.totalCf.guarantor}</span>
              </p>
            </td>
            <td>
              <p>
                <span>{outsideInstitution.outsideTotal.openCf}</span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {outsideInstitution.outsideTotal.totalOutstanding.borrower}
                </span>
              </p>
              <p>
                <span>
                  (
                  {
                    outsideInstitution.outsideTotal.totalOutstanding
                      .borrowerPercentage
                  }
                  )
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {outsideInstitution.outsideTotal.totalOutstanding.guarantor}
                </span>
              </p>
              <p>
                <span>
                  (
                  {
                    outsideInstitution.outsideTotal.totalOutstanding
                      .guarantorPercentage
                  }
                  )
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {outsideInstitution.outsideTotal.latestCFOpenedDate}
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {outsideInstitution.outsideTotal.delinquentCf.borrower}
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {outsideInstitution.outsideTotal.delinquentCf.guarantor}
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {
                    outsideInstitution.outsideTotal.delinquentOutstanding
                      .borrower
                  }
                </span>
              </p>
              <p>
                <span>
                  (
                  {
                    outsideInstitution.outsideTotal.delinquentOutstanding
                      .borrowerPercentage
                  }
                  )
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>
                  {
                    outsideInstitution.outsideTotal.delinquentOutstanding
                      .guarantor
                  }
                </span>
              </p>
              <p>
                <span>
                  (
                  {
                    outsideInstitution.outsideTotal.delinquentOutstanding
                      .guarantorPercentage
                  }
                  )
                </span>
              </p>
            </td>
          </tr>
          <tr>
            <td>
              <p>Total</p>
            </td>
            <td>
              <p>
                <span>{total.totalLenders}</span>
              </p>
            </td>
            <td colspan="2">
              <p>
                <span>{total.totalCf}</span>
              </p>
            </td>
            <td>
              <p>
                <span>{total.openCf}</span>
              </p>
            </td>
            <td colspan="2">
              <p>
                <span>{total.totalOutstanding}</span>
              </p>
            </td>
            <td>
              <p>
                <span>{total.latestCfOpenedDate}</span>
              </p>
            </td>
            <td colspan="2">
              <p>
                <span>{total.delinquentCf}</span>
              </p>
            </td>
            <td colspan="2">
              <p>
                <span>{total.delinquentOutstanding}</span>
              </p>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  );
}

export default CommercialCreditVision;
