import "../App.css";

function EnquirySummary({ base }) {
  const enquiryOutsideInstitution =
    base.data.report.productSec.enquirySummarySec.enquiryOutsideInstitution
      .noOfEnquiries;
  const enquiryYourInstitution =
    base.data.report.productSec.enquirySummarySec.enquiryYourInstitution
      .noOfEnquiries;
  const enquiryTotal =
    base.data.report.productSec.enquirySummarySec.enquiryTotal.noOfEnquiries;
  return (
    <div style={{ display: "flex", justifyContent: "center", margin: 50 }}>
      <table cellspacing="0" cellpadding="0">
        <thead>
          <tr>
            <th colspan="9">
              <p>5. Enquiry Summary</p>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <p>No. of Enquiries (In recent months)</p>
            </td>
            <td>
              <p>1</p>
            </td>
            <td>
              <p>2-3</p>
            </td>
            <td>
              <p>4-6</p>
            </td>
            <td>
              <p>7-12</p>
            </td>
            <td>
              <p>12-24</p>
            </td>
            <td>
              <p>24</p>
            </td>
            <td>
              <p>Total</p>
            </td>
            <td>
              <p>Most Recent</p>
            </td>
          </tr>
          <tr>
            <td>
              <p>Your Institution</p>
            </td>
            <td>
              <p>
                <span>{enquiryYourInstitution.month1}</span>
              </p>
            </td>
            <td>
              <p>
                <span>{enquiryYourInstitution.month2to3}</span>
              </p>
            </td>
            <td>
              <p>
                <span>{enquiryYourInstitution.month4to6}</span>
              </p>
            </td>
            <td>
              <p>
                <span>{enquiryYourInstitution.month7to12}</span>
              </p>
            </td>
            <td>
              <p>
                <span>{enquiryYourInstitution.month12to24}</span>
              </p>
            </td>
            <td>
              <p>
                <span>{enquiryYourInstitution.greaterThan24Month}</span>
              </p>
            </td>
            <td>
              <p>
                <span>{enquiryYourInstitution.total}</span>
              </p>
            </td>
            <td>
              <p>
                <span>{enquiryYourInstitution.mostRecentDate}</span>
              </p>
            </td>
          </tr>
          <tr>
            <td>
              <p>Outside</p>
            </td>
            <td>
              <p>
                <span>{enquiryOutsideInstitution.month1}</span>
              </p>
            </td>
            <td>
              <p>
                <span>{enquiryOutsideInstitution.month2to3}</span>
              </p>
            </td>
            <td>
              <p>
                <span>{enquiryOutsideInstitution.month4to6}</span>
              </p>
            </td>
            <td>
              <p>
                <span>{enquiryOutsideInstitution.month7to12}</span>
              </p>
            </td>
            <td>
              <p>
                <span>{enquiryOutsideInstitution.month12to24}</span>
              </p>
            </td>
            <td>
              <p>
                <span>{enquiryOutsideInstitution.greaterThan24Month}</span>
              </p>
            </td>
            <td>
              <p>
                <span>{enquiryOutsideInstitution.total}</span>
              </p>
            </td>
            <td>
              <p>
                <span>{enquiryOutsideInstitution.mostRecentDate}</span>
              </p>
            </td>
          </tr>
          <tr>
            <td>
              <p>Total</p>
            </td>
            <td>
              <p>
                <span>{enquiryTotal.month1}</span>
              </p>
            </td>
            <td>
              <p>
                <span>{enquiryTotal.month2to3}</span>
              </p>
            </td>
            <td>
              <p>
                <span>{enquiryTotal.month4to6}</span>
              </p>
            </td>
            <td>
              <p>
                <span>{enquiryTotal.month7to12}</span>
              </p>
            </td>
            <td>
              <p>
                <span>{enquiryTotal.month12to24}</span>
              </p>
            </td>
            <td>
              <p>
                <span>{enquiryTotal.greaterThan24Month}</span>
              </p>
            </td>
            <td>
              <p>
                <span>{enquiryTotal.total}</span>
              </p>
            </td>
            <td>
              <p>
                <span>{enquiryTotal.mostRecentDate}</span>
              </p>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  );
}

export default EnquirySummary;
