import "../App.css";

function OutstandingBalancesByCreditFacilityGroups({ base }) {
  const outsideInstitution = base.data.report.productSec.oustandingBalanceByCFAndAssetClasificationSec.outsideInstitution
  const yourInstitution = base.data.report.productSec.oustandingBalanceByCFAndAssetClasificationSec.yourInstitution
  return (
    <div style={{ display: "flex", justifyContent: "center", margin: 40 }}>
      <table cellspacing="0" cellpadding="0">
        <thead>
          <tr>
            <th colspan="11">
              <p>
                7. Outstanding Balances by Credit Facility Groups and Asset Classification
              </p>
              <p>
              # - No. of Credit Facilities; ₹ - Outstanding Balance in ₹
              </p>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td colspan="11">
              <p>
              (Depicted as No. of Facilities and corresponding Outstanding Balances under each CF Group and Asset Class. bucket.)
              </p>
            </td>
          </tr>
          <tr>
            <td rowspan="2">
              <p>
                CF GROUP
              </p>
            </td>
            <td colspan="4">
              <p>
                STD
              </p>
            </td>
            <td colspan="5">
              <p>
                NON-STD
              </p>
            </td>
            <td rowspan="2">
              <p>
                TOTAL
              </p>
            </td>
          </tr>
          <tr>
            <td>
              <p>
                0 DPD
              </p>
            </td>
            <td>
              <p>
              1-30 DPD / SMA 0
              </p>
            </td>
            <td>
              <p>
              31-60 DPD / SMA 1
              </p>
            </td>
            <td>
              <p>
              61-90 DPD / SMA 2
              </p>
            </td>
            <td>
              <p>
                91-180 DPD
              </p>
            </td>
            <td>
              <p>
              &nbsp; 180 DPD
              </p>
            </td>
            <td>
              <p>
                SUB
              </p>
            </td>
            <td>
              <p>
                DBT
              </p>
            </td>
            <td>
              <p>
                LOSS
              </p>
            </td>
          </tr>
          <tr>
            <td colspan="11">
              <p>
                Your Institution
              </p>
            </td>
          </tr>
          <tr>
            <td>
            <p>
              <span>&nbsp;</span>
              </p>
              <p>
                Not Funded
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.nonFunded.stdVec.dpd0.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.nonFunded.stdVec.dpd1To30.value.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.nonFunded.stdVec.dpd31To60.value.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.nonFunded.stdVec.dpd61To90.value.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.nonFunded.nonStdVec.dpd91To180.value.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.nonFunded.nonStdVec.greaterThan180Dpd.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.nonFunded.nonStdVec.sub.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.nonFunded.nonStdVec.dbt.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.nonFunded.nonStdVec.loss.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.nonFunded.total.value
                  }
                </span>
              </p>
            </td>
          </tr>
          <tr>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                  Working Capital
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.workingCapital.stdVec.dpd0.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.workingCapital.stdVec.dpd1To30.value.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.workingCapital.stdVec.dpd31To60.value.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.workingCapital.stdVec.dpd61To90.value.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.workingCapital.nonStdVec.dpd91To180.value.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.workingCapital.nonStdVec.greaterThan180Dpd.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.workingCapital.nonStdVec.sub.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.workingCapital.nonStdVec.dbt.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.workingCapital.nonStdVec.loss.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.workingCapital.total.value
                  }
                </span>
              </p>
            </td>
          </tr>
          <tr>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                  Term Loan
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.termLoan.stdVec.dpd0.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.termLoan.stdVec.dpd1To30.value.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.termLoan.stdVec.dpd31To60.value.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.termLoan.stdVec.dpd61To90.value.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.termLoan.nonStdVec.dpd91To180.value.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.termLoan.nonStdVec.greaterThan180Dpd.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.termLoan.nonStdVec.sub.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.termLoan.nonStdVec.dbt.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.termLoan.nonStdVec.loss.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.termLoan.total.value
                  }
                </span>
              </p>
            </td>
          </tr>
          <tr>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                  Forex
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.forex.stdVec.dpd0.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.forex.stdVec.dpd1To30.value.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.forex.stdVec.dpd31To60.value.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.forex.stdVec.dpd61To90.value.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.forex.nonStdVec.dpd91To180.value.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.forex.nonStdVec.greaterThan180Dpd.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.forex.nonStdVec.sub.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.forex.nonStdVec.dbt.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.forex.nonStdVec.loss.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.forex.total.value
                  }
                </span>
              </p>
            </td>
          </tr>
          <tr>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                Total
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.total.stdVec.dpd0.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.total.stdVec.dpd1To30.value.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.total.stdVec.dpd31To60.value.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.total.stdVec.dpd61To90.value.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.total.nonStdVec.dpd91To180.value.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.total.nonStdVec.greaterThan180Dpd.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.total.nonStdVec.sub.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.total.nonStdVec.dbt.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.total.nonStdVec.loss.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    yourInstitution.total.total.value
                  }
                </span>
              </p>
            </td>
          </tr>
          <tr>
            <td colspan="16">
              <p>
                Outside
              </p>
            </td>
          </tr>
          <tr>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                  Not Funded
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.nonFunded.stdVec.dpd0.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.nonFunded.stdVec.dpd1To30.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.nonFunded.stdVec.dpd31To60.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.nonFunded.stdVec.dpd61To90.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.nonFunded.stdVec.dpd61To90.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.nonFunded.nonStdVec.greaterThan180Dpd.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.nonFunded.nonStdVec.sub.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.nonFunded.nonStdVec.dbt.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.nonFunded.nonStdVec.loss.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.nonFunded.total.value
                  }
                </span>
              </p>
            </td>
          </tr>
          <tr>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                Working Capital
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.workingCapital.stdVec.dpd0.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.workingCapital.stdVec.dpd1To30.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.workingCapital.stdVec.dpd31To60.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.workingCapital.stdVec.dpd61To90.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.workingCapital.nonStdVec.dpd91To180.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.workingCapital.nonStdVec.greaterThan180Dpd.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.workingCapital.nonStdVec.sub.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.workingCapital.nonStdVec.dbt.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.workingCapital.nonStdVec.loss.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.workingCapital.total.value
                  }
                </span>
              </p>
            </td>
          </tr>
          <tr>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                  Term Loan
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.termLoan.stdVec.dpd0.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.termLoan.stdVec.dpd1To30.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.termLoan.stdVec.dpd31To60.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.termLoan.stdVec.dpd61To90.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.termLoan.nonStdVec.dpd91To180.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.termLoan.nonStdVec.greaterThan180Dpd.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.termLoan.nonStdVec.sub.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.termLoan.nonStdVec.dbt.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.termLoan.nonStdVec.loss.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.termLoan.total.value
                  }
                </span>
              </p>
            </td>
          </tr>
          <tr>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                Forex
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.forex.stdVec.dpd0.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.forex.stdVec.dpd1To30.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.forex.stdVec.dpd31To60.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.forex.stdVec.dpd61To90.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.forex.nonStdVec.dpd91To180.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.forex.nonStdVec.greaterThan180Dpd.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.forex.nonStdVec.sub.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.forex.nonStdVec.dbt.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.forex.nonStdVec.loss.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.forex.total.value
                  }
                </span>
              </p>
            </td>
          </tr>
          <tr>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                Total
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.total.stdVec.dpd0.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.total.stdVec.dpd1To30.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.total.stdVec.dpd31To60.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.total.stdVec.dpd61To90.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.total.nonStdVec.dpd91To180.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.total.nonStdVec.greaterThan180Dpd.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.total.nonStdVec.sub.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.total.nonStdVec.dbt.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.total.nonStdVec.loss.value
                  }
                </span>
              </p>
            </td>
            <td>
              <p>
                <span>&nbsp;</span>
              </p>
              <p>
                <span>
                  {
                    outsideInstitution.total.value
                  }
                </span>
              </p>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  );
}

export default OutstandingBalancesByCreditFacilityGroups;
